### ISSUE TITLE
manage discrete repo of workflows, share as volume

### ISSUE THREAD

**Issue by bertsky** [slub/ocrd_manager#46]
The Monitor must have read access (soon also: write access) to the repository of workflow scripts. Currently they are deployed in the Manager container only.

Proposal: a dedicated path within the `shared` volume, optionally under git version control. Workflows are copied to the process directory prior to processing.

**Comment by SvenMarcus** [comment]
Additionally, I suggest introducing a workflow mount directory where users can place their workflow files (and also the required models?).

**Comment by bertsky** [comment]
> (and also the required models?).

That already exists (volume `/models`), but on the Controller (naturally).

> I suggest introducing a workflow mount directory

Indeed, this should be a bind-mount, not a shared volume.
