### ISSUE TITLE
Symlink for_production.sh and for_production.sh

### ISSUE THREAD

**Issue by markusweigelt** [slub/ocrd_manager#50]
Inside the container these scripts are no symbolic links to process_images.sh and process_mets.sh but separate scripts. Probably the copy process in the Dockerfile resolves symbolic links. Therefore the linking must be done within the Dockerfile. The existing symbolic links in the repository can be removed.

**Comment by bertsky** [comment]
Oh, indeed! Yes, I'll make it a RUN ln.

> The existing symbolic links in the repository can be removed.

I'd rather keep them, though. – for illustration, and for native / non-docker users.
